### ISSUE TITLE
Found a BUG in your code. 

### ISSUE THREAD

**Issue by Twistere** [Reachip/e621#1]
When I put this command in my  terminal`python3 main.py [clothing] [thread workers]` the code send me an error `Traceback (most recent call last):
  File "main.py", line 91, in <module>
    with ProcessPoolExecutor(max_workers=int(sys.argv[2])) as executor:
ValueError: invalid literal for int() with base 10: '[thread'
macbook-pro-de-antunes:e621-master lucas$  python3 main.py [clothing] [thread workers]
`
Please fix this bug.(Il marche pas ton code.)

**Comment by Reachip** [comment]
As much for me, this CLI is very badly documented actually. You just have to replace [clothing] by the categorie that you want and [thread workers] by the number of threads (CPU simultaneous task) that you want to have to.

For example : 

```
python3 main.py smile 2
```

**Comment by Twistere** [comment]
Clothing c'est une catégorie Janus mais merci de l'aide
